const $=id=>document.getElementById(id);
const board=$('board'),scoreEl=$('score'),bestEl=$('best'),coinsEl=$('coins'),targetEl=$('target'),comboEl=$('combo'),groupsEl=$('groups'),streakEl=$('streak'),groupScoreEl=$('groupScore'),missionKicker=$('missionKicker'),tip=$('tip'),toast=$('toast'),reward=$('reward');
const COLORS=['#ff477e','#ffb703','#36d399','#38bdf8','#8b5cf6','#fb7185','#22d3ee','#a3e635'];
const SHOP=[{id:'pink',name:'Neon Pink',color:'#ff477e',cost:50},{id:'gold',name:'Electric Gold',color:'#ffb703',cost:50},{id:'green',name:'Lime Glow',color:'#36d399',cost:75},{id:'cyan',name:'Aqua Cyan',color:'#22d3ee',cost:75},{id:'purple',name:'Galaxy Purple',color:'#8b5cf6',cost:100},{id:'blue',name:'Sky Blue',color:'#38bdf8',cost:100},{id:'lime',name:'Laser Lime',color:'#a3e635',cost:150},{id:'rainbow',name:'Rainbow',color:'rainbow',cost:250}];
const POINTS={2:10,3:30,4:50,6:75,9:100};
const STAGES=[2,3,4,6,9];
let state={score:+localStorage.getItem('grid_score')||0,best:+localStorage.getItem('grid_best')||0,coins:+localStorage.getItem('grid_coins')||0,target:2,selected:null,groups:0,combo:0,cycle:0,rainbowChance:.06,sound:true,daily:+localStorage.getItem('grid_daily')||0,day:localStorage.getItem('grid_day')||new Date().toDateString(),activeColor:localStorage.getItem('grid_active_color')||'pink',owned:JSON.parse(localStorage.getItem('grid_owned')||'["pink"]')};
let groups=[];
let nextId=1;
let swipeStart=null;
if(state.day!==new Date().toDateString()){state.day=new Date().toDateString();state.daily=0;localStorage.setItem('grid_daily',0);}
function save(){localStorage.setItem('grid_score',state.score);localStorage.setItem('grid_best',state.best);localStorage.setItem('grid_coins',state.coins);localStorage.setItem('grid_daily',state.daily);localStorage.setItem('grid_day',state.day);localStorage.setItem('grid_active_color',state.activeColor);localStorage.setItem('grid_owned',JSON.stringify(state.owned));}
function update(){scoreEl.textContent=state.score.toLocaleString();bestEl.textContent=state.best.toLocaleString();coinsEl.textContent=state.coins.toLocaleString();targetEl.textContent=state.target;comboEl.textContent=state.combo;groupsEl.textContent=state.groups;streakEl.textContent=state.combo;groupScoreEl.textContent='+'+(POINTS[state.target]||10);missionKicker.textContent=state.target===9?'FINAL CUBE':state.target===6?'BUILD 3×3':'NEXT MERGE';$('dailyText').textContent=`Match ${Math.min(state.daily,20)}/20 groups`;$('dailyModalCount').textContent=Math.min(state.daily,20);$('dailyBar').style.width=Math.min(100,state.daily*5)+'%';}
function pickColor(){const active=SHOP.find(x=>x.id===state.activeColor);const palette=active&&active.color!=='rainbow'?[active.color,...COLORS.filter(c=>c!==active.color)]:COLORS;return palette[Math.floor(Math.random()*palette.length)];}
function allowedShape(size,w,h){if(size===2)return(w===2&&h===1)||(w===1&&h===2);if(size===3)return(w===3&&h===1)||(w===1&&h===3);if(size===4)return w===2&&h===2;if(size===6)return(w===3&&h===2)||(w===2&&h===3);if(size===9)return w===3&&h===3;return false;}
function cellsInfo(cells){const rows=cells.map(i=>Math.floor(i/6)),cols=cells.map(i=>i%6);const minR=Math.min(...rows),maxR=Math.max(...rows),minC=Math.min(...cols),maxC=Math.max(...cols);return{minR,maxR,minC,maxC,w:maxC-minC+1,h:maxR-minR+1};}
function isRect(cells){const info=cellsInfo(cells);return cells.length===info.w*info.h;}
function adjacent(a,b){const A=new Set(a.cells);for(const x of b.cells){const r=Math.floor(x/6),c=x%6;for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]]){const n=(r+dr)*6+(c+dc);if(A.has(n))return true;}}return false;}
function compatible(a,b){if(!adjacent(a,b))return false;const size=a.cells.length+b.cells.length;if(!POINTS[size])return false;const cells=[...a.cells,...b.cells];return isRect(cells)&&allowedShape(size,cellsInfo(cells).w,cellsInfo(cells).h);}
function sameColor(a,b){return a.rainbow||b.rainbow||a.color===b.color;}
function makeGroup(cells,color=pickColor(),rainbow=Math.random()<state.rainbowChance){return{id:nextId++,cells:[...cells].sort((a,b)=>a-b),color,rainbow};}
function renderBoard(){board.innerHTML='';board.style.gridTemplateRows='repeat(6,minmax(0,1fr))';board.style.aspectRatio='1';groups.forEach(g=>{const info=cellsInfo(g.cells);const el=document.createElement('button');el.className=`tile group-${g.cells.length}`+(g.rainbow?' rainbow':'')+(state.selected===g.id?' selected':'');el.dataset.group=g.id;el.setAttribute('aria-label',`${g.cells.length} block ${g.rainbow?'rainbow':'color'}`);el.style.gridColumn=`${info.minC+1} / span ${info.w}`;el.style.gridRow=`${info.minR+1} / span ${info.h}`;el.style.aspectRatio='auto';if(!g.rainbow)el.style.setProperty('--c',g.color);el.innerHTML=g.cells.length>1?`<span class="merge-size">${g.cells.length}</span>`:'';el.onclick=()=>selectGroup(g.id);board.appendChild(el);});}
function occupied(){const s=new Set();groups.forEach(g=>g.cells.forEach(c=>s.add(c)));return s;}
function findGroup(id){return groups.find(g=>g.id===id);}
function ensureStartingPair(){for(let i=0;i<groups.length;i++){for(let j=i+1;j<groups.length;j++){if(adjacent(groups[i],groups[j])){groups[j].color=groups[i].color;groups[j].rainbow=false;return;}}}}
function ensureNextMatch(source){for(const g of groups){if(g.id===source.id)continue;if(adjacent(source,g)&&compatible(source,g)){g.color=source.color;g.rainbow=false;return true;}}return false;}
function randomEmptyCell(){const used=occupied(),free=[];for(let i=0;i<36;i++)if(!used.has(i))free.push(i);return free.length?free[Math.floor(Math.random()*free.length)]:null;}
function spawnRandomTile(){const cell=randomEmptyCell();if(cell===null)return false;groups.push(makeGroup([cell]));return true;}
function makeBoard(){groups=[];state.selected=null;nextId=1;const cells=[...Array(36).keys()];for(let i=cells.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cells[i],cells[j]]=[cells[j],cells[i]];}for(let i=0;i<28;i++)groups.push(makeGroup([cells[i]]));ensureStartingPair();ensureNextMatch(groups[0]);renderBoard();tip.textContent='👆 Swipe the board up, down, left or right to bring matching colors together.';}
function canShift(g,dr,dc,placed){const next=g.cells.map(c=>{const r=Math.floor(c/6)+dr,col=c%6+dc;return r*6+col;});for(let i=0;i<next.length;i++){const r=Math.floor(next[i]/6),c=next[i]%6;if(r<0||r>=6||c<0||c>=6)return false;if(placed.has(next[i]))return false;}return next;}
function slideBoard(dir){const [dr,dc]=dir==='up'?[-1,0]:dir==='down'?[1,0]:dir==='left'?[0,-1]:[0,1];const ordered=[...groups].sort((a,b)=>{const ca=a.cells.map(x=>x%6),cb=b.cells.map(x=>x%6),ra=a.cells.map(x=>Math.floor(x/6)),rb=b.cells.map(x=>Math.floor(x/6));if(dir==='left')return Math.min(...ca)-Math.min(...cb);if(dir==='right')return Math.max(...cb)-Math.max(...ca);if(dir==='up')return Math.min(...ra)-Math.min(...rb);return Math.max(...rb)-Math.max(...ra);});
const placed=new Set();let moved=false;for(const g of ordered){let cells=g.cells;while(true){const next=canShift({...g,cells},dr,dc,placed);if(!next)break;cells=next;moved=true;}g.cells=cells.sort((a,b)=>a-b);g.cells.forEach(c=>placed.add(c));}
if(moved){state.selected=null;spawnRandomTile();playTone('match');toastMsg(dir==='left'?'← Shifted':dir==='right'?'→ Shifted':dir==='up'?'↑ Shifted':'↓ Shifted');save();renderBoard();update();}
return moved;}
function selectGroup(id){const g=findGroup(id);if(!g)return;if(state.selected===id){state.selected=null;renderBoard();return;}if(state.selected===null){state.selected=id;tip.textContent=g.cells.length>1?'Now tap a touching group with the same color.':'Tap a side-by-side matching color.';renderBoard();return;}const first=findGroup(state.selected);state.selected=null;if(!first){renderBoard();return;}if(!sameColor(first,g)){markBad(first.id,g.id);tip.textContent='👀 Same color and side-by-side only.';return;}if(!compatible(first,g)){markBad(first.id,g.id);tip.textContent='↔️ Those shapes cannot form the next clean block.';return;}mergeGroups(first,g);}
function markBad(a,b){[a,b].forEach(id=>{const el=board.querySelector(`[data-group="${id}"]`);el?.classList.add('bad');setTimeout(()=>el?.classList.remove('bad'),300);});}
function mergeGroups(a,b){const cells=[...a.cells,...b.cells].sort((x,y)=>x-y);const size=cells.length;const color=pickColor();groups=groups.filter(g=>g.id!==a.id&&g.id!==b.id);const merged=makeGroup(cells,color,false);groups.push(merged);state.groups++;state.combo++;state.daily=Math.min(20,state.daily+1);state.score+=POINTS[size];state.best=Math.max(state.best,state.score);state.target=STAGES.find(x=>x>size)||9;if(size===9){state.coins+=100;state.target=2;playTone('coin');reward.classList.remove('hidden');setTimeout(()=>reward.classList.add('hidden'),1400);tip.textContent='💎 3×3 cube complete! +100 coins. Keep growing.';setTimeout(()=>clearMega(merged.id),650);}else{playTone('match');toastMsg(state.combo>=3?`🔥 ${state.combo}× merge +${POINTS[size]}`:`+${POINTS[size]} — ${size}-block created`);tip.textContent=size===6?'🧩 Build a 3×3 cube from the 6-block.':size===4?'⚡ Grow it into a 6-block or make another 4-block.':size===3?'✨ Two or more blocks can grow again.':'🎨 The merged block changed color — swipe to bring its matching neighbor closer.';ensureNextMatch(merged);}save();update();renderBoard();}
function clearMega(id){const g=findGroup(id);if(!g)return;groups=groups.filter(x=>x.id!==id);g.cells.forEach(cell=>{if(!occupied().has(cell))groups.push(makeGroup([cell]));});ensureStartingPair();spawnRandomTile();renderBoard();save();update();}
function toastMsg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),900);}
let audioCtx;function playTone(kind){if(!state.sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=kind==='coin'?720:420;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.16);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.17);}catch(e){}}
function renderShop(){const list=$('shopList');list.innerHTML='';SHOP.forEach(item=>{const owned=state.owned.includes(item.id),active=state.activeColor===item.id;const b=document.createElement('button');b.className='shop-item'+(active?' active':'');b.innerHTML=`<span class="shop-swatch ${item.color==='rainbow'?'rainbow':''}" style="--c:${item.color==='rainbow'?'#fff':item.color}"></span><span class="shop-name"><b>${item.name}</b><small>${active?'EQUIPPED':owned?'UNLOCKED':item.cost+' 🪙'}</small></span><strong>${active?'✓':owned?'USE':item.cost+' 🪙'}</strong>`;b.onclick=()=>buyColor(item);list.appendChild(b);});}
function buyColor(item){if(state.owned.includes(item.id)){state.activeColor=item.id;save();renderShop();toastMsg(`🎨 ${item.name} equipped`);return;}if(state.coins<item.cost){toastMsg(`Need ${item.cost-state.coins} more 🪙`);return;}state.coins-=item.cost;state.owned.push(item.id);state.activeColor=item.id;save();update();renderShop();playTone('coin');toastMsg(`✨ ${item.name} unlocked!`);}
function handleSwipe(dx,dy){if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;slideBoard(Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'up':'down'));}
board.addEventListener('touchstart',e=>{if(e.touches.length===1)swipeStart={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});
board.addEventListener('touchend',e=>{if(!swipeStart)return;const t=e.changedTouches[0];handleSwipe(t.clientX-swipeStart.x,t.clientY-swipeStart.y);swipeStart=null;},{passive:true});
board.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')return;swipeStart={x:e.clientX,y:e.clientY};});
board.addEventListener('pointerup',e=>{if(e.pointerType!=='mouse'||!swipeStart)return;handleSwipe(e.clientX-swipeStart.x,e.clientY-swipeStart.y);swipeStart=null;});
window.addEventListener('keydown',e=>{const keys={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down'};const dir=keys[e.key];if(dir){e.preventDefault();slideBoard(dir);}});
$('restart').onclick=()=>{state.score=0;state.target=2;state.selected=null;state.combo=0;state.groups=0;tip.textContent='✨ New board. Swipe to bring matching colors together.';save();update();makeBoard();};
$('soundBtn').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'♪':'×';toastMsg(state.sound?'Sound on':'Sound off');if(state.sound)playTone('match');};
$('shopBtn').onclick=()=>{$('shopModal').classList.remove('hidden');renderShop();};$('closeShop').onclick=()=>$('shopModal').classList.add('hidden');
$('dailyBtn').onclick=()=>$('dailyModal').classList.remove('hidden');$('closeDaily').onclick=()=>$('dailyModal').classList.add('hidden');$('playDaily').onclick=()=>{$('dailyModal').classList.add('hidden');toastMsg('🎯 Daily challenge active!');};
$('shareBtn').onclick=async()=>{const text=`I scored ${state.score.toLocaleString()} on Gridly! 🧩🔥 Can you beat me?`;try{if(navigator.share)await navigator.share({title:'Gridly',text});else await navigator.clipboard.writeText(text);toastMsg('↗ Score ready to share!');}catch(e){}};
update();makeBoard();window.addEventListener('load',()=>{setTimeout(()=>$('splash')?.classList.add('hide'),1900);});
