const $=id=>document.getElementById(id);
const board=$('board'),scoreEl=$('score'),bestEl=$('best'),coinsEl=$('coins'),targetEl=$('target'),comboEl=$('combo'),groupsEl=$('groups'),streakEl=$('streak'),groupScoreEl=$('groupScore'),missionKicker=$('missionKicker'),tip=$('tip'),toast=$('toast'),reward=$('reward');
const COLORS=['#ff477e','#ffb703','#36d399','#38bdf8','#8b5cf6','#fb7185','#22d3ee','#a3e635'];
const SHOP=[{id:'pink',name:'Neon Pink',color:'#ff477e',cost:50},{id:'gold',name:'Electric Gold',color:'#ffb703',cost:50},{id:'green',name:'Lime Glow',color:'#36d399',cost:75},{id:'cyan',name:'Aqua Cyan',color:'#22d3ee',cost:75},{id:'purple',name:'Galaxy Purple',color:'#8b5cf6',cost:100},{id:'blue',name:'Sky Blue',color:'#38bdf8',cost:100},{id:'lime',name:'Laser Lime',color:'#a3e635',cost:150},{id:'rainbow',name:'Rainbow',color:'rainbow',cost:250}];
let state={score:+localStorage.getItem('grid_score')||0,best:+localStorage.getItem('grid_best')||0,coins:+localStorage.getItem('grid_coins')||0,target:2,selected:[],groups:0,combo:0,cycle:0,rainbowChance:.06,sound:true,daily:+localStorage.getItem('grid_daily')||0,day:localStorage.getItem('grid_day')||new Date().toDateString(),activeColor:localStorage.getItem('grid_active_color')||'pink',owned:JSON.parse(localStorage.getItem('grid_owned')||'["pink"]')};
if(state.day!==new Date().toDateString()){state.day=new Date().toDateString();state.daily=0;localStorage.setItem('grid_daily',0);}
const points={2:10,3:30,4:50,5:65,6:75,7:85,8:95,9:100};
function save(){localStorage.setItem('grid_score',state.score);localStorage.setItem('grid_best',state.best);localStorage.setItem('grid_coins',state.coins);localStorage.setItem('grid_daily',state.daily);localStorage.setItem('grid_day',state.day);localStorage.setItem('grid_active_color',state.activeColor);localStorage.setItem('grid_owned',JSON.stringify(state.owned));}
function update(){scoreEl.textContent=state.score.toLocaleString();bestEl.textContent=state.best.toLocaleString();coinsEl.textContent=state.coins.toLocaleString();targetEl.textContent=state.target;comboEl.textContent=state.combo;groupsEl.textContent=state.groups;streakEl.textContent=state.combo;groupScoreEl.textContent='+'+(points[state.target]||100);missionKicker.textContent=state.target===9?'FINAL COMBO':'NEXT COMBO';$('dailyText').textContent=`Match ${Math.min(state.daily,20)}/20 groups`;$('dailyModalCount').textContent=Math.min(state.daily,20);$('dailyBar').style.width=Math.min(100,state.daily*5)+'%';}
function pickColor(){const active=SHOP.find(x=>x.id===state.activeColor);const palette=active&&active.color!=='rainbow'?[active.color,...COLORS.filter(c=>c!==active.color)]:COLORS;return palette[Math.floor(Math.random()*palette.length)]}
function makeTile(color=pickColor(),rainbow=false){const el=document.createElement('button');el.className='tile';el.dataset.color=rainbow?'rainbow':color;if(rainbow)el.classList.add('rainbow');else el.style.setProperty('--c',color);el.setAttribute('aria-label',rainbow?'Rainbow wild card':'Color tile');el.addEventListener('click',()=>selectTile(el));return el;}
function ensureTargetGroup(){const tiles=[...board.children];const n=Math.min(state.target,tiles.length);const color=pickColor();const available=tiles.filter(t=>!state.selected.includes(t));for(let i=0;i<n&&i<available.length;i++){const t=available[i];t.classList.remove('rainbow');t.dataset.color=color;t.style.setProperty('--c',color);}}
function makeBoard(){board.innerHTML='';state.selected=[];for(let i=0;i<36;i++){const rainbow=Math.random()<state.rainbowChance;board.appendChild(makeTile(pickColor(),rainbow));}ensureTargetGroup();}
function refillTiles(){const count=state.selected.length;state.selected.forEach(x=>{x.classList.add('pop');setTimeout(()=>x.remove(),220)});setTimeout(()=>{for(let i=0;i<count;i++)board.appendChild(makeTile(pickColor(),Math.random()<state.rainbowChance));ensureTargetGroup();},230);}
function selectTile(el){if(state.selected.includes(el))return;if(state.selected.length===0){state.selected.push(el);el.classList.add('selected');return}const first=state.selected[0];const same=first.dataset.color===el.dataset.color||first.dataset.color==='rainbow'||el.dataset.color==='rainbow';if(!same){state.selected.forEach(x=>{x.classList.add('bad');setTimeout(()=>x.classList.remove('bad','selected'),280)});state.selected=[];tip.textContent='👀 Same color — or use the rainbow wild card!';return;}state.selected.push(el);el.classList.add('selected');if(state.selected.length===state.target)completeGroup();}
function completeGroup(){const n=state.target,earned=points[n]||100;state.score+=earned;state.best=Math.max(state.best,state.score);state.groups++;state.combo++;state.daily=Math.min(20,state.daily+1);if(state.combo>=3)toastMsg(`🔥 ${state.combo}× combo +${earned}`);else toastMsg(`+${earned} points`);playTone(n===9?'coin':'match');if(n===9){state.coins+=100;reward.classList.remove('hidden');setTimeout(()=>reward.classList.add('hidden'),1300);state.target=2;state.combo=0;state.cycle++;tip.textContent='💎 3×3 complete! +100 coins. New group starts at 2.';}else{state.target=n+1;tip.textContent=n>=5?'⚡ Bigger group! Keep going.':'✨ New boxes are dropping in. Keep growing!';}refillTiles();save();update();}
function toastMsg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),900)}
let audioCtx;function playTone(kind){if(!state.sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=kind==='coin'?720:420;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.16);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.17);}catch(e){}}
function renderShop(){const list=$('shopList');list.innerHTML='';SHOP.forEach(item=>{const owned=state.owned.includes(item.id),active=state.activeColor===item.id;const b=document.createElement('button');b.className='shop-item'+(active?' active':'');b.innerHTML=`<span class="shop-swatch ${item.color==='rainbow'?'rainbow':''}" style="--c:${item.color==='rainbow'?'#fff':item.color}"></span><span class="shop-name"><b>${item.name}</b><small>${active?'EQUIPPED':owned?'UNLOCKED':item.cost+' 🪙'}</small></span><strong>${active?'✓':owned?'USE':item.cost+' 🪙'}</strong>`;b.onclick=()=>buyColor(item);list.appendChild(b);});}
function buyColor(item){if(state.owned.includes(item.id)){state.activeColor=item.id;save();renderShop();toastMsg(`🎨 ${item.name} equipped`);return;}if(state.coins<item.cost){toastMsg(`Need ${item.cost-state.coins} more 🪙`);return;}state.coins-=item.cost;state.owned.push(item.id);state.activeColor=item.id;save();update();renderShop();playTone('coin');toastMsg(`✨ ${item.name} unlocked!`);}
$('restart').onclick=()=>{state.score=0;state.target=2;state.selected=[];state.combo=0;state.groups=0;tip.textContent='✨ Fresh run. How far can you grow?';save();update();makeBoard();};
$('soundBtn').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'♪':'×';toastMsg(state.sound?'Sound on':'Sound off');if(state.sound)playTone('match')};
$('shopBtn').onclick=()=>{$('shopModal').classList.remove('hidden');renderShop()};$('closeShop').onclick=()=>$('shopModal').classList.add('hidden');
$('dailyBtn').onclick=()=>$('dailyModal').classList.remove('hidden');$('closeDaily').onclick=()=>$('dailyModal').classList.add('hidden');$('playDaily').onclick=()=>{$('dailyModal').classList.add('hidden');toastMsg('🎯 Daily challenge active!')};
$('shareBtn').onclick=async()=>{const text=`I scored ${state.score.toLocaleString()} on Gridly! 🧩🔥 Can you beat me?`;try{if(navigator.share)await navigator.share({title:'Gridly',text});else await navigator.clipboard.writeText(text);toastMsg('↗ Score ready to share!')}catch(e){}};
update();makeBoard();window.addEventListener('load',()=>{setTimeout(()=>$('splash')?.classList.add('hide'),1900)});
